apiVersion: v1
data:
          otel-collector-config.yaml: |-
                  # Copyright The OpenTelemetry Authors
                  # SPDX-License-Identifier: Apache-2.0
                  # imported from https://github.com/mdelapenya/junit2otlp
                  receivers:
                    jaeger:
                      protocols:
                        thrift_compact:
                    otlp:
                      protocols:
                        grpc:
                        http:

                  exporters:
                    logging:
                      loglevel: debug
                    file:
                      path: /tmp/tests.json
                    jaeger:
                      endpoint: jaeger-all-in-one:14250
                      tls:
                        insecure: true
                    otlp:
                      endpoint: tempo-eu-west-0.grafana.net:443
                      headers:
                        authorization: Basic MyKey

                  processors:
                    batch:

                  extensions:
                    health_check:
                    pprof:
                      endpoint: :1888
                    zpages:
                      endpoint: :55679

                  service:
                    extensions: [pprof, zpages, health_check]
                    pipelines:
                      traces:
                        receivers: [otlp]
                        processors: [batch]
                        exporters: [logging, jaeger,otlp]
                      metrics:
                        receivers: [otlp]
                        processors: [batch]
                        exporters: [logging]
kind: ConfigMap
metadata:
          creationTimestamp: null
          name: otel-collector-config-yaml